keychain:
  applogic:
    algorithm: RS256
    value: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2RXRpK055dkxINU1GdmM0WXk4TgpFenU2SWt4UWs0eDhLb1JOYjQrNEJXN0tTcnZzVTZyYStQVkI0aG9DL2lsbGRNbDA2TmowaE5NZnd4N1RKUzBlCkNGVEJjdEc4c01XaEl1cFdCeUhZSGczMTFUMWJ4ZGo4TjRaZExybFRmY2pXUUZPQWFsSHNuRitIRE5ZNWRsVzEKQVlFT0NZUHBpOXNpeFBSdlZGeVR3ZUh4a0p1dFRBcFpleWl6M1JqRkJGdXY4Qjl5R3dla3VmbzJ3dUM2WHlORQplS0ZuWkhnQzdualNGVjZMY21PWEVNOWtUNWhBL1ZIcG1IUUhxaDFVNmFJREVOR0dnVWliT1RGNkQxdUJQdEZLCjBlR1EzbFdtRDQwMjYvY2hqWWhtYkhWMldWL1VyN2ozTFB4WHcyWDF6QnhUUFJlOUFTNFVUVEJOY3dBLzU4ajAKK1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

scopes:
  read_operations:
    mandatory_signers:
      - applogic
    permitted_signers:
      - applogic

jwt: {}
