class Banner < BaseModel
  skip_default_columns

  STATES = %w[active deleted]

  table do
    primary_key id : Int32

    column uuid : UUID
    column url : String
    column state : String = "active"

    column created_at : Time, autogenerated: true
    column updated_at : Time, autogenerated: true
  end

  def self.create(**args)
    SaveBanner.create!(**args)
  end

  def to_json
    {
      id:                         id,
      uuid:                       uuid,
      url:                        url,
      state:                      state,
      created_at:                 created_at,
      updated_at:                 updated_at
    }
  end

  def for_public
    {
      uuid:             uuid,
      url:              url
    }
  end
end
