class Broadcast < BaseModel
  skip_default_columns

  table do
    primary_key id : Int32

    column url : String
    column title : String
    column state : String = "active"

    column created_at : Time, autogenerated: true
    column updated_at : Time, autogenerated: true
  end

  def self.create(**args)
    SaveBroadcast.create!(**args)
  end

  def to_json
    {
      id:                         id,
      url:                        url,
      title:                      title,
      state:                      state,
      created_at:                 created_at,
      updated_at:                 updated_at
    }
  end

  def for_public
    {
      url:              url,
      title:            title
    }
  end
end
