class Code < BaseModel
  skip_default_columns

  table do
    primary_key id : Int32

    column type : String
    column email : String?
    column phone : String?
    column code : String = rand.to_s[2, 7]
    column attempts : Int32 = 0
    column validated_at : Time?
    column expired_at : Time

    column created_at : Time, autogenerated: true
    column updated_at : Time, autogenerated: true
  end

  def self.create(**args)
    SaveCode.create!(**args)
  end
end
