class Code < BaseModel
  skip_default_columns

  TYPES = ["withdraw", "register", "reset_password"]

  table do
    primary_key id : Int32

    column type : String
    column email : String
    column confirmation_code : String
    column attempts : Int32 = 0
    column validated_at : Time?
    column expired_at : Time

    column created_at : Time, autogenerated: true
    column updated_at : Time, autogenerated: true
  end

  def self.create(**args)
    SaveCode.create!(**args)
  end

  def to_json
    {
      type:                   type,
      email:                  email,
      confirmation_code:      confirmation_code,
      attempts:               attempts,
      validated_at:           validated_at,
      expired_at:             expired_at,
      created_at:             created_at,
      updated_at:             updated_at,
    }
  end
end
